version: '3.9'

networks:
  microservice_net:
    name: msn

services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    networks:
      microservice_net:

  message-broker:
    build:
      context: .
      dockerfile: MessageBroker/Dockerfile
    networks:
      microservice_net:
      

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    networks:
      microservice_net:

  tweet-service:
    build:
      context: .
      dockerfile: TweetService/Dockerfile
    networks:
      microservice_net:
