version: '3.9'


services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - 8082:80


  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - 8081:80
    depends_on:
      gateway:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - 8083:80
    depends_on:
      gateway:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  tweet-service:
    build:
      context: .
      dockerfile: TweetService/Dockerfile
    ports:
      - 8084:80
    depends_on:
      gateway:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"


  user-sql:
    container_name: MySQL-user
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - '3307:3306'
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd) [https://github.com/docker-library/mysql/issues/873]
        soft: 1048576
        hard: 1048576
    volumes:
      - user-service-vol:/var/lib/mysql
  
  tweet-sql:
    container_name: MySQL-tweet
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: database_user
      MYSQL_PASSWORD: Password1!
    ports:
      - '3308:3306'
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd) [https://github.com/docker-library/mysql/issues/873]
        soft: 1048576
        hard: 1048576
    volumes:
      - tweet-service-vol:/var/lib/mysql
  
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LISTEN_ADDRESS=0.0.0.0
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage

  zipkin-storage:
    image: openzipkin/zipkin-mysql
    volumes:
      - zipkin_data:/mysql/data
  
volumes:
    tweet-service-vol:
    user-service-vol:
    rps_seq_data:
    zipkin_data: