version: '3.9'

networks:
  microservice_net:
    name: msn

services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    networks:
      microservice_net:

  messageBroker:
    build:
      context: .
      dockerfile: MessageBroker/Dockerfile
    networks:
      microservice_net:
      

  userService:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    networks:
      microservice_net:

  tweetService:
    build:
      context: .
      dockerfile: TweetService/Dockerfile
    networks:
      microservice_net:
